const meta = {
  'bars-since': '',
  'cross': '',
  'cross-over': '',
  'cross-under': '',
  'fill-region': '',
  'first': '',
  'gap-down': '',
  'gap-up': '',
  'hhv': '',
  'hhv-bars': '',
  'highest': '',
  'highest-bars': '',
  'highest-since': '',
  'highest-since-bars': '',
  'inside': '',
  'last-value': '',
  'llv': '',
  'llv-bars': '',
  'lowest': '',
  'lowest-bars': '',
  'lowest-since': '',
  'lowest-since-bars': '',
  'outside': '',
  'peak': '',
  'peak-bars': '',
  'proj-band-top': '',
  'rally': '',
  'rally-with-volume': '',
  'reaction': '',
  'reaction-with-volume': '',
  'reference': '',
  'set-name': '',
  'ste-band-bot': '',
  'ste-band-top': '',
  'trough': '',
  'trough-bars': '',
  'value-when': ''
};

export default meta;
